import {
  FileEdit,
  Archive,
  Merge,
  Split,
  RefreshCw,
  Signature,
  Lock,
  Unlock,
  ScanText,
  ImageIcon,
  Crop,
  Video,
  Music,
  Film,
  FileArchive,
  FileSpreadsheet,
  Database,
  Info,
  FileText,
  Wrench,
} from "lucide-react";
import { ToolConfig } from "../../components/dialogs/FileUploadDialog";

export const toolConfigs: Record<string, ToolConfig> = {
  // PDF Tools
  "edit-pdf": {
    id: "edit-pdf",
    name: "Edit PDF",
    icon: FileEdit,
    acceptedTypes: ["application/pdf"],
    acceptedExtensions: [".pdf"],
    multiple: false,
    description: "Add text, images, and annotations to your PDF",
    actionLabel: "Start Editing",
  },
  "compress-pdf": {
    id: "compress-pdf",
    name: "Compress PDF",
    icon: Archive,
    acceptedTypes: ["application/pdf"],
    acceptedExtensions: [".pdf"],
    multiple: false,
    description: "Reduce PDF file size while maintaining quality",
    actionLabel: "Compress Now",
  },
  "repair-pdf": {
    id: "repair-pdf",
    name: "Repair PDF",
    icon: Wrench,
    acceptedTypes: ["application/pdf"],
    acceptedExtensions: [".pdf"],
    multiple: true,
    description: "Fix corrupted or damaged PDF files",
    actionLabel: "Repair PDF",
  },
  "merge-pdf": {
    id: "merge-pdf",
    name: "Merge PDF",
    icon: Merge,
    acceptedTypes: ["application/pdf"],
    acceptedExtensions: [".pdf"],
    multiple: true,
    minFiles: 2,
    description: "Combine multiple PDF files into one",
    actionLabel: "Merge Files",
  },
  "split-pdf": {
    id: "split-pdf",
    name: "Split PDF",
    icon: Split,
    acceptedTypes: ["application/pdf"],
    acceptedExtensions: [".pdf"],
    multiple: false,
    description: "Extract pages from your PDF",
    actionLabel: "Split PDF",
  },
  "convert-to-pdf": {
    id: "convert-to-pdf",
    name: "Convert to PDF",
    icon: RefreshCw,
    acceptedTypes: [
      "application/msword",
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      "application/vnd.ms-excel",
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      "application/vnd.ms-powerpoint",
      "application/vnd.openxmlformats-officedocument.presentationml.presentation",
      "image/*",
    ],
    acceptedExtensions: [".doc", ".docx", ".xls", ".xlsx", ".ppt", ".pptx", ".jpg", ".png"],
    multiple: true,
    description: "Convert Word, Excel, PowerPoint, and images to PDF",
    actionLabel: "Convert to PDF",
  },
  "convert-from-pdf": {
    id: "convert-from-pdf",
    name: "Convert from PDF",
    icon: RefreshCw,
    acceptedTypes: ["application/pdf"],
    acceptedExtensions: [".pdf"],
    multiple: false,
    description: "Convert PDF to Word, Excel, or PowerPoint",
    actionLabel: "Convert PDF",
  },
  "convert-pdf-to-word": {
    id: "convert-pdf-to-word",
    name: "Convert PDF to Word",
    icon: FileText,
    acceptedTypes: ["application/pdf"],
    acceptedExtensions: [".pdf"],
    multiple: false,
    description: "Convert PDF to editable DOCX format",
    actionLabel: "Convert to Word",
  },
  "sign-pdf": {
    id: "sign-pdf",
    name: "Sign PDF",
    icon: Signature,
    acceptedTypes: ["application/pdf"],
    acceptedExtensions: [".pdf"],
    multiple: false,
    description: "Add your digital signature to PDF documents",
    actionLabel: "Sign Document",
  },
  "protect-pdf": {
    id: "protect-pdf",
    name: "Protect PDF",
    icon: Lock,
    acceptedTypes: ["application/pdf"],
    acceptedExtensions: [".pdf"],
    multiple: false,
    description: "Add password protection to your PDF",
    actionLabel: "Protect PDF",
  },
  "unlock-pdf": {
    id: "unlock-pdf",
    name: "Unlock PDF",
    icon: Unlock,
    acceptedTypes: ["application/pdf"],
    acceptedExtensions: [".pdf"],
    multiple: false,
    description: "Remove password protection from PDF",
    actionLabel: "Unlock PDF",
  },
  "unlock-protect-pdf": {
    id: "unlock-protect-pdf",
    name: "Unlock / Protect PDF",
    icon: Lock,
    acceptedTypes: ["application/pdf"],
    acceptedExtensions: [".pdf"],
    multiple: false,
    description: "Add or remove password protection from PDFs",
    actionLabel: "Continue",
  },
  "redact-pdf": {
    id: "redact-pdf",
    name: "Redact PDF",
    icon: Lock,
    acceptedTypes: ["application/pdf"],
    acceptedExtensions: [".pdf"],
    multiple: false,
    description: "Permanently remove sensitive information from PDFs",
    actionLabel: "Redact PDF",
  },
  "ocr-pdf": {
    id: "ocr-pdf",
    name: "OCR PDF",
    icon: ScanText,
    acceptedTypes: ["application/pdf"],
    acceptedExtensions: [".pdf"],
    multiple: false,
    description: "Extract text from scanned PDFs",
    actionLabel: "Start OCR",
  },

  // Image Tools
  "jpg-to-png": {
    id: "jpg-to-png",
    name: "JPG to PNG",
    icon: ImageIcon,
    acceptedTypes: ["image/jpeg", "image/png"],
    acceptedExtensions: [".jpg", ".jpeg", ".png"],
    multiple: true,
    description: "Convert JPG to PNG format",
    actionLabel: "Convert Images",
  },
  "jpg-png": {
    id: "jpg-png",
    name: "JPG ↔ PNG",
    icon: ImageIcon,
    acceptedTypes: ["image/jpeg", "image/png"],
    acceptedExtensions: [".jpg", ".jpeg", ".png"],
    multiple: true,
    description: "Convert between JPG and PNG formats instantly",
    actionLabel: "Convert Images",
  },
  "png-to-webp": {
    id: "png-to-webp",
    name: "PNG to WEBP",
    icon: ImageIcon,
    acceptedTypes: ["image/png", "image/webp"],
    acceptedExtensions: [".png", ".webp"],
    multiple: true,
    description: "Convert PNG to modern WEBP format",
    actionLabel: "Convert Images",
  },
  "webp-to-avif": {
    id: "webp-to-avif",
    name: "WEBP to AVIF",
    icon: ImageIcon,
    acceptedTypes: ["image/webp", "image/avif"],
    acceptedExtensions: [".webp", ".avif"],
    multiple: true,
    description: "Convert WEBP to next-gen AVIF format",
    actionLabel: "Convert Images",
  },
  "jpg-png-webp-avif": {
    id: "jpg-png-webp-avif",
    name: "JPG ↔ PNG / WEBP / AVIF",
    icon: ImageIcon,
    acceptedTypes: ["image/jpeg", "image/png", "image/webp", "image/avif"],
    acceptedExtensions: [".jpg", ".jpeg", ".png", ".webp", ".avif"],
    multiple: true,
    description: "Convert between image formats",
    actionLabel: "Convert Images",
  },
  "compress-image": {
    id: "compress-image",
    name: "Compress Image",
    icon: Archive,
    acceptedTypes: ["image/*"],
    acceptedExtensions: [".jpg", ".jpeg", ".png", ".webp"],
    multiple: true,
    description: "Reduce image file size",
    actionLabel: "Compress Images",
  },
  "resize-image": {
    id: "resize-image",
    name: "Resize Image",
    icon: Crop,
    acceptedTypes: ["image/*"],
    acceptedExtensions: [".jpg", ".jpeg", ".png", ".webp"],
    multiple: false,
    description: "Change image dimensions",
    actionLabel: "Resize Image",
  },
  "crop-image": {
    id: "crop-image",
    name: "Crop Image",
    icon: Crop,
    acceptedTypes: ["image/*"],
    acceptedExtensions: [".jpg", ".jpeg", ".png", ".webp"],
    multiple: false,
    description: "Trim your images",
    actionLabel: "Crop Image",
  },
  "resize-crop-image": {
    id: "resize-crop-image",
    name: "Resize / Crop Image",
    icon: Crop,
    acceptedTypes: ["image/*"],
    acceptedExtensions: [".jpg", ".jpeg", ".png", ".webp"],
    multiple: false,
    description: "Change dimensions or trim your images",
    actionLabel: "Edit Image",
  },
  "image-to-pdf": {
    id: "image-to-pdf",
    name: "Image to PDF",
    icon: RefreshCw,
    acceptedTypes: ["image/*"],
    acceptedExtensions: [".jpg", ".jpeg", ".png", ".webp"],
    multiple: true,
    description: "Convert images to PDF",
    actionLabel: "Convert to PDF",
  },
  "pdf-to-image": {
    id: "pdf-to-image",
    name: "PDF to Image",
    icon: RefreshCw,
    acceptedTypes: ["application/pdf"],
    acceptedExtensions: [".pdf"],
    multiple: false,
    description: "Extract PDF pages as images",
    actionLabel: "Convert to Images",
  },
  "image-pdf": {
    id: "image-pdf",
    name: "Image ↔ PDF",
    icon: RefreshCw,
    acceptedTypes: ["image/*", "application/pdf"],
    acceptedExtensions: [".jpg", ".jpeg", ".png", ".webp", ".pdf"],
    multiple: true,
    description: "Convert images to PDF or PDF to images",
    actionLabel: "Convert",
  },

  // Video Tools
  "mp4-to-webm": {
    id: "mp4-to-webm",
    name: "MP4 to WEBM",
    icon: Video,
    acceptedTypes: ["video/*"],
    acceptedExtensions: [".mp4", ".webm"],
    multiple: false,
    description: "Convert MP4 to web-friendly WEBM format",
    actionLabel: "Convert Video",
  },
  "webm-to-mov": {
    id: "webm-to-mov",
    name: "WEBM to MOV",
    icon: Video,
    acceptedTypes: ["video/*"],
    acceptedExtensions: [".webm", ".mov"],
    multiple: false,
    description: "Convert WEBM to MOV format",
    actionLabel: "Convert Video",
  },
  "mov-to-avi": {
    id: "mov-to-avi",
    name: "MOV to AVI",
    icon: Video,
    acceptedTypes: ["video/*"],
    acceptedExtensions: [".mov", ".avi"],
    multiple: false,
    description: "Convert MOV to legacy AVI format",
    actionLabel: "Convert Video",
  },
  "mp4-webm-mov-avi": {
    id: "mp4-webm-mov-avi",
    name: "MP4 ↔ WEBM / MOV / AVI",
    icon: Video,
    acceptedTypes: ["video/*"],
    acceptedExtensions: [".mp4", ".webm", ".mov", ".avi"],
    multiple: false,
    description: "Convert between video formats",
    actionLabel: "Convert Video",
  },
  "compress-video": {
    id: "compress-video",
    name: "Compress Video",
    icon: Archive,
    acceptedTypes: ["video/*"],
    acceptedExtensions: [".mp4", ".webm", ".mov", ".avi"],
    multiple: false,
    description: "Reduce video file size",
    actionLabel: "Compress Video",
  },
  "trim-video": {
    id: "trim-video",
    name: "Trim Video",
    icon: Split,
    acceptedTypes: ["video/*"],
    acceptedExtensions: [".mp4", ".webm", ".mov", ".avi"],
    multiple: false,
    description: "Cut video clips",
    actionLabel: "Trim Video",
  },
  "merge-video": {
    id: "merge-video",
    name: "Merge Video",
    icon: Merge,
    acceptedTypes: ["video/*"],
    acceptedExtensions: [".mp4", ".webm", ".mov", ".avi"],
    multiple: true,
    minFiles: 2,
    description: "Join multiple video files",
    actionLabel: "Merge Videos",
  },
  "trim-merge-video": {
    id: "trim-merge-video",
    name: "Trim / Merge Video",
    icon: Split,
    acceptedTypes: ["video/*"],
    acceptedExtensions: [".mp4", ".webm", ".mov", ".avi"],
    multiple: true,
    description: "Cut video clips or join multiple videos",
    actionLabel: "Edit Video",
  },
  "video-to-audio": {
    id: "video-to-audio",
    name: "Video to Audio",
    icon: Music,
    acceptedTypes: ["video/*"],
    acceptedExtensions: [".mp4", ".webm", ".mov", ".avi"],
    multiple: false,
    description: "Extract audio track from video",
    actionLabel: "Extract Audio",
  },
  "video-to-gif": {
    id: "video-to-gif",
    name: "Video to GIF",
    icon: Film,
    acceptedTypes: ["video/*"],
    acceptedExtensions: [".mp4", ".webm", ".mov"],
    multiple: false,
    description: "Create animated GIF from video",
    actionLabel: "Convert to GIF",
  },
  "video-audio": {
    id: "video-audio",
    name: "Video ↔ Audio",
    icon: Music,
    acceptedTypes: ["video/*", "audio/*"],
    acceptedExtensions: [".mp4", ".webm", ".mov", ".mp3", ".wav"],
    multiple: false,
    description: "Extract audio from video or add audio to video",
    actionLabel: "Convert",
  },
  "video-gif": {
    id: "video-gif",
    name: "Video ↔ GIF",
    icon: Film,
    acceptedTypes: ["video/*", "image/gif"],
    acceptedExtensions: [".mp4", ".webm", ".mov", ".gif"],
    multiple: false,
    description: "Convert video to GIF or GIF to video",
    actionLabel: "Convert",
  },

  // Audio Tools
  "mp3-to-wav": {
    id: "mp3-to-wav",
    name: "MP3 to WAV",
    icon: Music,
    acceptedTypes: ["audio/*"],
    acceptedExtensions: [".mp3", ".wav"],
    multiple: true,
    description: "Convert MP3 to lossless WAV format",
    actionLabel: "Convert Audio",
  },
  "wav-to-ogg": {
    id: "wav-to-ogg",
    name: "WAV to OGG",
    icon: Music,
    acceptedTypes: ["audio/*"],
    acceptedExtensions: [".wav", ".ogg"],
    multiple: true,
    description: "Convert WAV to OGG format",
    actionLabel: "Convert Audio",
  },
  "ogg-to-mp3": {
    id: "ogg-to-mp3",
    name: "OGG to MP3",
    icon: Music,
    acceptedTypes: ["audio/*"],
    acceptedExtensions: [".ogg", ".mp3"],
    multiple: true,
    description: "Convert OGG to universal MP3 format",
    actionLabel: "Convert Audio",
  },
  "mp3-wav-ogg": {
    id: "mp3-wav-ogg",
    name: "MP3 ↔ WAV / OGG",
    icon: Music,
    acceptedTypes: ["audio/*"],
    acceptedExtensions: [".mp3", ".wav", ".ogg"],
    multiple: true,
    description: "Convert between audio formats",
    actionLabel: "Convert Audio",
  },
  "trim-audio": {
    id: "trim-audio",
    name: "Trim Audio",
    icon: Split,
    acceptedTypes: ["audio/*"],
    acceptedExtensions: [".mp3", ".wav", ".ogg"],
    multiple: false,
    description: "Cut audio clips",
    actionLabel: "Trim Audio",
  },
  "compress-audio": {
    id: "compress-audio",
    name: "Compress Audio",
    icon: Archive,
    acceptedTypes: ["audio/*"],
    acceptedExtensions: [".mp3", ".wav", ".ogg"],
    multiple: false,
    description: "Reduce audio file size",
    actionLabel: "Compress Audio",
  },

  // Other Tools
  "zip-files": {
    id: "zip-files",
    name: "ZIP Files",
    icon: FileArchive,
    acceptedTypes: ["*/*"],
    acceptedExtensions: [],
    multiple: true,
    minFiles: 2,
    description: "Compress multiple files into ZIP archive",
    actionLabel: "Create ZIP",
  },
  "unzip-files": {
    id: "unzip-files",
    name: "Unzip Files",
    icon: FileArchive,
    acceptedTypes: ["application/zip", "application/x-rar-compressed", "application/x-7z-compressed"],
    acceptedExtensions: [".zip", ".rar", ".7z"],
    multiple: false,
    description: "Extract archive contents",
    actionLabel: "Extract Files",
  },
  "zip-unzip-files": {
    id: "zip-unzip-files",
    name: "ZIP / Unzip Files",
    icon: FileArchive,
    acceptedTypes: ["*/*"],
    acceptedExtensions: [".zip", ".rar", ".7z"],
    multiple: true,
    description: "Compress multiple files or extract archives",
    actionLabel: "Process Files",
  },
  "csv-to-xlsx": {
    id: "csv-to-xlsx",
    name: "CSV to XLSX",
    icon: FileSpreadsheet,
    acceptedTypes: ["text/csv"],
    acceptedExtensions: [".csv"],
    multiple: false,
    description: "Convert CSV to Excel format",
    actionLabel: "Convert to XLSX",
  },
  "xlsx-to-csv": {
    id: "xlsx-to-csv",
    name: "XLSX to CSV",
    icon: FileSpreadsheet,
    acceptedTypes: ["application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"],
    acceptedExtensions: [".xlsx"],
    multiple: false,
    description: "Convert Excel to simple CSV format",
    actionLabel: "Convert to CSV",
  },
  "csv-to-json": {
    id: "csv-to-json",
    name: "CSV to JSON",
    icon: Database,
    acceptedTypes: ["text/csv"],
    acceptedExtensions: [".csv"],
    multiple: false,
    description: "Convert CSV data to JSON format",
    actionLabel: "Convert to JSON",
  },
  "json-to-csv": {
    id: "json-to-csv",
    name: "JSON to CSV",
    icon: Database,
    acceptedTypes: ["application/json"],
    acceptedExtensions: [".json"],
    multiple: false,
    description: "Export JSON data to CSV",
    actionLabel: "Convert to CSV",
  },
  "csv-xlsx-json": {
    id: "csv-xlsx-json",
    name: "CSV ↔ XLSX ↔ JSON",
    icon: FileSpreadsheet,
    acceptedTypes: ["text/csv", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "application/json"],
    acceptedExtensions: [".csv", ".xlsx", ".json"],
    multiple: false,
    description: "Convert between data formats",
    actionLabel: "Convert",
  },
  "batch-convert": {
    id: "batch-convert",
    name: "Batch Convert",
    icon: RefreshCw,
    acceptedTypes: ["*/*"],
    acceptedExtensions: [],
    multiple: true,
    description: "Convert multiple files at once",
    actionLabel: "Convert All",
  },
  "file-info": {
    id: "file-info",
    name: "File Info",
    icon: Info,
    acceptedTypes: ["*/*"],
    acceptedExtensions: [],
    multiple: false,
    description: "View file details",
    actionLabel: "Analyze File",
  },
  "file-hash": {
    id: "file-hash",
    name: "File Hash",
    icon: Info,
    acceptedTypes: ["*/*"],
    acceptedExtensions: [],
    multiple: false,
    description: "Generate file checksums",
    actionLabel: "Generate Hash",
  },
  "file-info-hash": {
    id: "file-info-hash",
    name: "File Info / Hash",
    icon: Info,
    acceptedTypes: ["*/*"],
    acceptedExtensions: [],
    multiple: false,
    description: "View file details and generate checksums",
    actionLabel: "Analyze File",
  },
};

// Helper function to get tool config by name
export const getToolConfigByName = (name: string): ToolConfig | null => {
  const key = Object.keys(toolConfigs).find(k => {
    const config = toolConfigs[k];
    return config.name === name;
  });
  return key ? toolConfigs[key] : null;
};